on:
    push:
        branches:
            - master
        paths:
            - ts-classnames/package.json

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Make stable release to npm
              uses: epeli/npm-release@v1
              with:
                  type: stable
                  dir: ts-classnames
                  token: ${{ secrets.NPM_TOKEN }}
